### PR TITLE
generated schema for the changes done for #698

### PR DESCRIPTION
**Pull request by krupalip**
Hi Grahame,

could you please review it?

Thanks
Krupali

### CODE REVIEW

**Comment by krupalip** [comment]
@grahame In regards to 'analytical_platform' It seems like they are not in the model. Only analysed models have them.

**Comment by grahame** [comment]
OK, great. Please merge this PR (note I've changed the base to be next_release, you should never merge straight onto master)

Once you've done that:

 - [ ] tag a release of ckanext-bpatheme and push it (remember to change setup.py)
 - [ ] update docker-bpa-ckan to use the new version of the theme
 - [ ] push that and tag a release of docker-bpa-ckan (no need for a PR)
 - [ ] update your dev environment and test

**Comment by krupalip** [comment]
Hey @grahame, how to update dev env and how to perform testing?

**Comment by ccgdev004** [comment]
I saw this in the GitHub feed and at the risk of being a busybody:

1. Stop all containers
2. In ```dockercompose-bpa-ckan```  repo:
type: docker-compose rm ckan

3. Go to ```docker-bpa-ckan``` repo:
type: ./develop.sh build

4. Go back to ```dockercompose-bpa-ckan``` repo:
type: docker-compose build
then type: docker-compose up

**Pull request merged**
